version: "3.7"
services:
    mariadb:
        build:
            context: .
            dockerfile: mariaDB/Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: db_notes
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - 3306:3306