version: '3'
services:

    backend:
        container_name: backend
        build:
            context: backend
            dockerfile: Dockerfile

        depends_on:
            - database
        restart: unless-stopped
        ports:
            - "4000:4000"
    frontend:
        container_name: frontend
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certs/cert.pem:/etc/nginx/ssl/cert.pem
            - ./certs/key.pem:/etc/nginx/ssl/key.pem
    database:
        container_name: database
        build:
            context: .
            dockerfile: mariaDB/Dockerfile
        env_file:
            - environment.env
        restart: always
        ports:
            - "3306:3306"
