version: '3'
services:

    backend:
        container_name: backend
        build:
            context: backend
            dockerfile: Dockerfile
        depends_on:
            - database
        restart: unless-stopped
        ports:
            - "4000:4000"
    frontend:
        container_name: frontend
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./cert/zertifikat.crt:/etc/nginx/ssl/cert.crt
            - ./cert/private.key:/etc/nginx/ssl/cert.key
    database:
        container_name: database
        build:
            context: .
            dockerfile: mariaDB/Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: keineGuteIdeedasHierReinZuSchreiben
            MYSQL_DATABASE: db_notes
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "3306:3306"
