name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./backend
        run:  npm ci    
      
      - name: start
        working-directory: ./backend
        run:  npm test
      - name: sleep
        working-directory: ./backend
        run: sleep 5
      - name: curl
        working-directory: ./backend
        run:  curl http://localhost:4000
